[package]
name = "vedaweb"
version = "0.1.0"
authors = ["ujjwalraajput <ujjwal.raajput@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
roxmltree = "0.4.1"
