[package]
name = "vedcksh"
version = "0.1.0"
authors = ["ujjwalraajput <ujjwal.raajput@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3.3.2", default-features = false }
vedaweb = { path = "../vedaweb" }
