[package]
name = "vedyogah"
version = "0.1.0"
authors = ["ujjvlh <ujjwal.raajput@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vedaweb = { path = "../vedaweb" }
